############################
## CHANGE THESE
############################

baseURL: "https://viogami.github.io/blog"
title: Violog

markup:
  highlight:
    style: onedark
  goldmark:
    renderer:
      unsafe: true
      

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
