############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 1
- name: Blog
  url: /blog/
  weight: 2
- name: Thinking
  url: /thinking/
  weight: 4
- name: Project
  url: /project/
  weight: 3
- name: About
  url: /about/
  weight: 5