############################
## Author
############################

author:
  name: viogami
  image: author.png
  greeting: "If you can coding, you must be a designer!😎"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/viogami/blog
  - steam: https://steamcommunity.com/id/viogami
  - email:  2654613995@qq.com
  - telegram: https://t.me/viogami
  - bilibili: https://space.bilibili.com/396367307
  - docker: https://hub.docker.com/repositories/viogami


  # - link: 
  # - website: 
  # - x-twitter: 
  # - mastodon: 
  # - linkedin: 
  # - instagram: 
  # - reddit: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: Violog
description: "Site build with Qubt & Hugo"
images:
  - thumbnail.png
